[[pages]]
path = "src/main_page.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "src/pages/apps_log.py"
name = "Applications Log"
icon = "ğŸ—‚ï¸"

[[pages]]
path = "src/pages/experiences.py"
name = "Experiences Log"
icon = "ğŸ§­"